export const role = [
  { name: "USER" },
  { name: "ADMIN" }
]

export const addressType = [
  { name: "Local Address" },
  { name: "Permanent Address" }
]

export const priority = [
  { name: "Low" },
  { name: "Medium" },
  { name: "High" }
]

export const application = [
  { name: "FINAID" },
  { name: "FINAID2" },
  { name: "ADMISSIONS" },
  { name: "USFAS" }
]

export const aidYear = [
  { name: "1314" },
  { name: "1415" },
  { name: "1516" },
  { name: "1617" },
  { name: "1718" },
  { name: "1819" },
  { name: "1920" },
  { name: "2021" },
  { name: "2122" },
  { name: "2223" },
  { name: "2324" }
]

export const title = [
  { name: "Director" },
  { name: "IT Support Specialist" },
  { name: "Technology & Systems Analyst" },
  { name: "Assistant Director" },
  { name: "Associate Director" },
  { name: "Financial Aid Team Manager" },
  { name: "Administrative Specialist" },
  { name: "Statistical Data Analyst" },
  { name: "Financial Aid Assistant" },
  { name: "Scholarship Team Manager" },
  { name: "Financial Aid Advisor" },
  { name: "Financial Aid Specialist" },
]

export const team = [
  { name: "Management" },
  { name: "Information Systems" },
  { name: "Bull-2-Bull" },
  { name: "Intake" },
  { name: "Electronic Processes" },
  { name: "Federal Grants" },
  { name: "Office Support" },
  { name: "Scholarships" },
  { name: "Team 1" },
  { name: "Team 2" },
  { name: "Team 3" },
  { name: "Team 4" },
  { name: "Verification" },
  { name: "College of Medicine" },
  { name: "College of Pharmacy" },
  { name: "Sarasota" },
  { name: "St. Pete" },
]

export const dataRequestType = [
  { name: "APEX" },
  { name: "Create Ad Hoc Report" },
  { name: "Update Ad Hoc Report" },
  { name: "Create Chrons" },
  { name: "Update Chrons" },
  { name: "Retire Chrons" },
  { name: "Create Population Selection" },
  { name: "Update Population Selection" },
  { name: "Refresh Population Selection" },
  { name: "Create ROREMAL" },
  { name: "Update ROREMAL" },
  { name: "Remove Rows From GURMAIL" },
  { name: "Database Update (DBU)" },
  { name: "UC4 - Create Chain" },
  { name: "UC4 - Update Chain" },
  { name: "UC4 - Create Module" },
  { name: "UC4 - Update Module" },
  { name: "Post To RRAAREQ" },
  { name: "Post To ROAHOLD" },
  { name: "Pre-Print" },
  { name: "Prior Term Loan Private Request" },
  { name: "Prior Term Loan DL Request" },
  { name: "Response File Reload Request" },
  { name: "Suspense Setup" },
  { name: "Private Loan Setup" },
  { name: "PWRA Schedule Request" }
]

export const requestType = [
  { name: "BDMS (Online) - Create" },
  { name: "BDMS (Online) - Update" },
  { name: "Computer Support (for IS Team or IT)" },
  { name: "Audio/Video Setup in Breakroom" },
  { name: "Copies" },
  { name: "Email - Create" },
  { name: "Email - Update" },
  { name: "Financial Education" },
  { name: "Intranet - Update" },
  { name: "Master Calendar - Create" },
  { name: "Master Calendar - Update" },
  { name: "Paper Form - Create" },
  { name: "Paper Form - Update" },
  { name: "Paper Letter - Create" },
  { name: "Paper Letter - Update" },
  { name: "Standard & Procedures" },
  { name: "Pre-Prints - Run Them" },
  { name: "Print Pending Letters" },
  { name: "Publication (flyers, signs, etc.)" },
  { name: "Retire/Archive" },
  { name: "ROREMAL - Create" },
  { name: "ROREMAL - Update" },
  { name: "Staff Portal - Add/Update" },
  { name: "Training Schedule - Add/Update" },
  { name: "General Training Library - Add/Update" },
  { name: "Website - Create" },
  { name: "Website - Update" },
  { name: "Population Selection" }
]

export const letterCode = [
  { name: "R-NEWSLETTER-E" },
  { name: "R-AIDPYMT-PT-E" },
  { name: "R-APR-E" },
  { name: "R-ARP-REMINDER-E" },
  { name: "R-ARPH-E" },
  { name: "R-ARPI-E" },
  { name: "R-ARPPJ-E" },
  { name: "R-AWARD-ERROR-E" },
  { name: "R-AWINCAP-E" },
  { name: "R-AWSCONT-E" },
  { name: "R-AWSPFTIC-E" },
  { name: "R-AWSTRGR-E" },
  { name: "R-B2BALLGRACE-E" },
  { name: "R-B2BALLGRCE2-E" },
  { name: "R-B2BBAL-E" },
  { name: "R-B2BBTBULL-E" },
  { name: "R-B2BBudg-E" },
  { name: "R-B2BCALLING-E" },
  { name: "R-B2BCALLSP-E" },
  { name: "R-B2BCALLSU-E" },
  { name: "R-B2BCREDIT-E" },
  { name: "R-B2BDELINQ" },
  { name: "R-B2BEARLY" },
  { name: "R-B2BEARLY-E" },
  { name: "R-B2BEXIT-E" },
  { name: "R-B2BEXIT2-E" },
  { name: "R-B2BFEDWEEK-E" },
  { name: "R-B2BINTRO-E" },
  { name: "R-B2BLATE" },
  { name: "R-B2BLATE-E" },
  { name: "R-B2BLOAN-E" },
  { name: "R-B2BMID" },
  { name: "R-B2BMID-E" },
  { name: "R-B2BNEWLOAN-E" },
  { name: "R-B2BNWSLTR-E" },
  { name: "R-B2BPELLOS-E" },
  { name: "R-B2BRESP-E" },
  { name: "R-B2BRFIN-E" },
  { name: "R-B2BSMB-E" },
  { name: "R-B2BSMRESP-E" },
  { name: "R-B2BSPRESP-E" },
  { name: "R-B2BTHEFT-E" },
  { name: "R-B2BVITA-E" },
  { name: "R-BANKRUPTCY" },
  { name: "R-BENHSDL-E" },
  { name: "R-BENHSNG-E" },
  { name: "R-BENREMF-E" },
  { name: "R-BF-AWD-CORR-E" },
  { name: "R-BF-EDURMV-E" },
  { name: "R-BF-REPAY-E" },
  { name: "R-BF-REPAYRETRO" },
  { name: "R-BF-SUMR-PSI-E" },
  { name: "R-BFFLPP-E" },
  { name: "R-BFFLPST-E" },
  { name: "R-BFSUMADJ-E" },
  { name: "R-BILL" },
  { name: "R-BNHSREMSP-E" },
  { name: "R-CARESPAY-E" },
  { name: "R-COA6YRM-E" },
  { name: "R-COASURVEY-E" },
  { name: "R-COMINTLAWD-E" },
  { name: "R-COMTRACK-E" },
  { name: "R-COVW-E" },
  { name: "R-CREDITBALANCE" },
  { name: "R-CRRSAH-RMF-E" },
  { name: "R-DEBTLETTER-E" },
  { name: "R-DEFER-BAL-E" },
  { name: "R-DFLTCURLTR" },
  { name: "R-DFLTMISSVCR" },
  { name: "R-DGRLVL3" },
  { name: "R-DISB_ERROR-E" },
  { name: "R-DISCHARGE-E" },
  { name: "R-DLDISB-E" },
  { name: "R-DOPDEN" },
  { name: "R-DOPINC" },
  { name: "R-EXAGLNBLD" },
  { name: "R-EXAGLNCHNG" },
  { name: "R-FAFSANOHS-E" },
  { name: "R-FAFSAREJECT-E" },
  { name: "R-FASCH-TC-E" },
  { name: "R-FBF-1GR-E" },
  { name: "R-FBF-ESTCROS-E" },
  { name: "R-FBF-FTICRNW-E" },
  { name: "R-FBF-HOURS-E" },
  { name: "R-FBF-MMRCROS-E" },
  { name: "R-FBF-SUMENRL-E" },
  { name: "R-FBF-SUMGRD-E" },
  { name: "R-FBF-SUMLTHT-E" },
  { name: "R-FBFNOTICE-E" },
  { name: "R-FBFSUM-E" },
  { name: "R-FHDV-E" },
  { name: "R-FHDV2-E" },
  { name: "R-FHDVBIL" },
  { name: "R-FIF-EMAIL" },
  { name: "R-FIFFRM-E" },
  { name: "R-FIN-ED-SURV-E" },
  { name: "R-FINAIDOFFER-E" },
  { name: "R-FINLIT101-E" },
  { name: "R-FLPR01" },
  { name: "R-FLPR02" },
  { name: "R-FLPR06" },
  { name: "R-FLPR07-E" },
  { name: "R-FLPR08-E" },
  { name: "R-FLPR10" },
  { name: "R-FLPR11" },
  { name: "R-FLPR15" },
  { name: "R-FLPR16" },
  { name: "R-FSAG_GRHRDEN" },
  { name: "R-FSAG_PETDEN" },
  { name: "R-FSAG_REPAY" },
  { name: "R-FSAG_REPAY2" },
  { name: "R-FSAG_REPAY3" },
  { name: "R-FTIC-RSRC-E" },
  { name: "R-FWS-OCEP-E" },
  { name: "R-FWSCONTPAY-E" },
  { name: "R-FWSNSAT-E" },
  { name: "R-FWSOFFER-E" },
  { name: "R-GGWVRSWP-E" },
  { name: "R-GPLSDISB-E" },
  { name: "R-GRAD-RSRC-E" },
  { name: "R-GRD-EMAIL" },
  { name: "R-INITIALAWD-E" },
  { name: "R-INITIALAWDX-E" },
  { name: "R-LEU-REPAY" },
  { name: "R-LNREPYARGNT" },
  { name: "R-LOAN-EOT-E" },
  { name: "R-LOANCANCL-E" },
  { name: "R-MDEXIT-E" },
  { name: "R-MID-ARC6M-E" },
  { name: "R-MISSINGMPN-E" },
  { name: "R-MIX4" },
  { name: "R-NLFALL-E" },
  { name: "R-NLSPR-E" },
  { name: "R-NLSU-E" },
  { name: "R-NMSSWP-E" },
  { name: "R-NOAWARD-EMAIL" },
  { name: "R-NOFAFSA-DEF-E" },
  { name: "R-NOFAFSACARE-E" },
  { name: "R-NOFAFSAPT-E" },
  { name: "R-NRA-ISSCANC-E" },
  { name: "R-NSLDSPENDAID" },
  { name: "R-OWD" },
  { name: "R-PELL-LEU" },
  { name: "R-PELL-LEU-E" },
  { name: "R-PELL15" },
  { name: "R-PENDINGPAIDLN" },
  { name: "R-PLSDENSUB" },
  { name: "R-PLSDISB" },
  { name: "R-PLSDISB-E" },
  { name: "R-PLUSDATA" },
  { name: "R-PLUSDEFAULT" },
  { name: "R-PLUSNOSAP" },
  { name: "R-PRVLCOAMET" },
  { name: "R-PRVLNOELIG" },
  { name: "R-PRVLNOSAP" },
  { name: "R-PRVLNOSSN" },
  { name: "R-PRVLNVERIFINC" },
  { name: "R-PT-OFFERS-E" },
  { name: "R-PT-VERIF-E" },
  { name: "R-PWD" },
  { name: "R-QUESTION-E" },
  { name: "R-REIN" },
  { name: "R-REPAY" },
  { name: "R-REPAY-BA-DEG" },
  { name: "R-REPAY-REVIEW" },
  { name: "R-REPAY_ND" },
  { name: "R-REPAY_SAP" },
  { name: "R-SAP_CAPFA-E" },
  { name: "R-SAP_CAPSP-E" },
  { name: "R-SAP_CAPSU-E" },
  { name: "R-SAP_MAXFA-E" },
  { name: "R-SAP_MAXSP-E" },
  { name: "R-SAP_MAXSU-E" },
  { name: "R-SAPPA" },
  { name: "R-SAPPD" },
  { name: "R-SAPPI" },
  { name: "R-SAPPNN" },
  { name: "R-SAPPROBGP" },
  { name: "R-SAPPROBMAX" },
  { name: "R-SATP-ERROR-E" },
  { name: "R-SCHAPPLY-E" },
  { name: "R-SCHAWDNF-E" },
  { name: "R-SCHOFRDNF-E" },
  { name: "R-SPSPET-A" },
  { name: "R-SPSPET-D" },
  { name: "R-SPSPET-S" },
  { name: "R-SSFSITRACK" },
  { name: "R-STALEDATED-E" },
  { name: "R-SUMAPP-EMAIL" },
  { name: "R-SUSP3RESUBMIT" },
  { name: "R-SWSSUM20-E" },
  { name: "R-TEACHD-E" },
  { name: "R-TEACHDISB-E" },
  { name: "R-TEACHEXIT-E" },
  { name: "R-TRACKINC" },
  { name: "R-TRK5" },
  { name: "R-UAS-LTFT-E" },
  { name: "R-UGSPET-A" },
  { name: "R-UGSPET-D" },
  { name: "R-UGSPET-S" },
  { name: "R-UGSPETSP-D" },
  { name: "R-UNSUBTOSUB" },
  { name: "R-USCH-HRSWRN-E" },
  { name: "R-USCH-MXTRM2-E" },
  { name: "R-USCH-NO2TRM-E" },
  { name: "R-USCH-NORENW-E" },
  { name: "R-USCH-REMFA-E" },
  { name: "R-USCH-SCHWRN-E" },
  { name: "R-USCH-TC-E" },
  { name: "R-USFP-N2TRM-E" },
  { name: "R-USFP-NORENW-E" },
  { name: "R-USFP-SCHWRN-E" },
  { name: "R-UWD-BILL" },
  { name: "R-UWD-E" },
  { name: "R-UWD-NOBILL" },
  { name: "R-UWDM-E" },
  { name: "R-VERIFDEN" },
  { name: "R-VERIFDEPI" },
  { name: "R-VERIFDEPSUP-E" },
  { name: "R-VERIFDEPV" },
  { name: "R-VERIFDRG" },
  { name: "R-VERIFDRGR" },
  { name: "R-VERIFETOD" },
  { name: "R-VERIFINC" },
  { name: "R-VERIFREPAY" },
  { name: "R-VERIFREVIEW-E" },
  { name: "R-VERIFVA" },
  { name: "R-VERIFXDL" },
  { name: "R-VLDA-E" },
  { name: "R-VLDA-ERROR-E" },
  { name: "R-VLDA-FORM" },
  { name: "R-VLDA2-E" },
  { name: "R-WGU-REM-E" },
  { name: "R-WGUPAY-E" },
  { name: "R-YRPELL-ELIG-E" }
]